const mongoose = require("mongoose");

const orderSchema = mongoose.Schema({
    shippingInfo:{
        addrease:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        phoneNo:{
            type:Number,
            required:true
        }
    },
    productInfo:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true
            },
            quantity:{
                type:Number,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            product:{
                type:mongoose.Schema.ObjectId,
                ref:"Product",
                required:true,
            }
        }
    ],
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"User",
        required:true,
    },
    paymentInfo:{
        id:{
            type:String,
            required:true
        },
        status:{
            type:String,
            required:true,
            default:"Procesing"
        },
        paidAt:{
            type:Date,
            required:true,
            default:Date.now()
        }
    },
    itemPrice:{
        type:Number,
        default:0,
        required:true
    },
    shippingPrice:{
        type:Number,
        default:0,
        required:true
    },
    totalPrice:{
        type:Number,
        default:0,
        required:true
    },
    orderStatus:{
        type:String,
        default:"Procesing",
    },
    createdAt:{
        type:Date,
        default:Date.now()
    },
    deliveredAt:Date,
});

// export
module.exports = mongoose.model("Order", orderSchema);